### ISSUE TITLE
Wrap swipe?

### ISSUE THREAD

**Issue by tverilytt** [SouhailBS/Ionic-AngularJS-Swipable-tabs#1]
Thanks a lot for this, it works great on first try on Android device.

Just wondering if it could be handy to allow "wrap swipe"?

E.g. if one have 3 tabs "One", "Two", Three". And when in tab "Three" swipe left, tab "One" could show up. And correspondingly, when swiping right when in tab "One", go to tab "Three".

Cheers
-jo

**Comment by SouhailBS** [comment]
By "wrap swipe" you mean something like a loop ?

**Comment by tverilytt** [comment]
@SouhailBS Yes, in the sense that one "continues to next" when swiping at "edge tabs".

Swipe left: One -> Two -> Three -> One -> Two...
Swipe right: One -> Three -> Two -> One -> Two...

**Comment by SouhailBS** [comment]
Feature added :)
Update your installation and check the [README.md](https://github.com/SouhailBS/Ionic-AngularJS-Swipable-tabs/blob/master/README.md) file for instructions.

**Comment by tverilytt** [comment]
Wow, kudos for that, works like a charm :-)
